# Site Settings
locale                   : "en"
title                    : "TheShellNut"
title_separator          : "-"
name                     : &authorName "Mathieu Buisson"
description              : "PowerShell, Automation, From Dev to Ops and Everything in Between"
url                      : "https://mathieubuisson.github.io"
baseurl                  : # the subpath of your site, e.g. "/blog"
repository               : "MathieuBuisson/MathieuBuisson.github.io"
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
# breadcrumbs            : false # true, false (default)
words_per_minute         : 175
comments:
  provider               : "staticman"
  disqus:
    shortname            : # https://help.disqus.com/customer/portal/articles/466208-what-s-a-shortname-
  discourse:
    server               : # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
  facebook:
    # https://developers.facebook.com/docs/plugins/comments
    appid                :
    num_posts            : #
    colorscheme          : # "light" (default), "dark"
staticman:
  # allowedFields          : ['name', 'email', 'url', 'message']
  branch                 : "develop"
  # commitMessage          : "New comment."
  # filename               : comment-{@timestamp}
  # format                 : "yml"
  # moderation             : true
  # path                   : "docs/_data/comments/{options.slug}" # "/_data/comments/{options.slug}" (default)
  # requiredFields         : ['name', 'email', 'message']
  # transforms:
    # email                : "md5"
  # generatedFields:
    # date:
      # type               : "date"
      # options:
        # format           : "iso8601" # "iso8601" (default), "timestamp-seconds", "timestamp-milliseconds"
atom_feed:
  path                   : # blank (default) uses feed.xml

# SEO Related
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :

# Social Sharing
twitter:
  username               : "TheShellNut"
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 : /assets/images/TheShellNut_Cropped-min.jpg
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : "TheShellNut"
  links: 
    - "https://twitter.com/TheShellNut"
    - "https://github.com/MathieuBuisson"
    - "https://www.linkedin.com/in/mathieubuisson"

# Analytics
analytics:
  provider               : "google-universal"
  google:
    tracking_id          : "UA-1682328-3"

# Site Author
author:
  name             : *authorName
  avatar           : "https://avatars0.githubusercontent.com/u/10233108?v=4&s=460"
  bio              : 'Automation partisan <br>PowerShell artisan <br>Continuous deployer <br>Perpetual learner <br>Doing "the DevOps" @OneviewHC'
  location         : "Ireland"
  email            :
  uri              :
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         :
  foursquare       :
  github           : "MathieuBuisson"
  gitlab           :
  google_plus      :
  keybase          :
  instagram        :
  lastfm           :
  linkedin         : "mathieubuisson"
  pinterest        :
  soundcloud       :
  stackoverflow    : # "123456/username" (the last part of your profile url, e.g. http://stackoverflow.com/users/123456/username)
  steam            :
  tumblr           :
  twitter          : "TheShellNut"
  vine             :
  weibo            :
  xing             :
  youtube          : # "https://youtube.com/c/MichaelRoseDesign"

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:title/
paginate: 10 # amount of posts to show
paginate_path: /page:num/
timezone: Europe/Dublin


# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development


# Defaults
defaults:
  # _posts
  -
    scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      author: "TheShellNut"
  -
    scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

# post with future date won't show
future: false

# For development purposes only !
webrick:
  headers:
    Access-Control-Allow-Origin: "*"
