_id: 1a83c840-6bef-11e8-a56e-fff0a43998e5
message: >-
  Thanks for the detailed blog post. I'll try this in one of my Windows projects
  soon.
name: Stefan Scherer
email: 0c09487dd4b63737bd5004333230a77b
url: 'https://stefanscherer.github.io'
hidden: ''
date: '2018-06-09T14:12:12.697Z'
tags:
  - comment-subscription
timestamp: 1528553532
